name: Deploy to Azure App Servce

on:
    push:
        branches:
            - main
jobs:
    buil-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions\checkout@v3

            - name: setup the node.js version
              uses: actions\setup-node@v4
              with:
                node-version: "18.x"

            - name: Install dependencies
              run: npm install 

            - name: Deploy to Azure App Service
              uses: azure\webapps-deploy@v2
              with:
                app-name: DeployNodeApp
                publish-profile: ${{secrets.MAZ_SECRET_DEPLOY}}
                packages: .
                